db_tier: db-f1-micro
app: syfo-arkivering
namespace: team-esyfo
team: team-esyfo
kafkaPool: nav-dev
azureTenant: trygdeetaten.no
ingress: https://syfo-arkivering.intern.dev.nav.no
cpu: 100m
memory: 600Mi
external-host:
  - dokarkiv.dev-fss-pub.nais.io
  - cdn.nav.no
env:
  SPRING_PROFILES_ACTIVE: default,testcontroller
  DOKARKIV_AAD_CLIENT_ID: dev-fss.teamdokumenthandtering.dokarkiv-q1
  DOKARKIV_URL: https://dokarkiv.dev-fss-pub.nais.io
