apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{image}}
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  {{#if ingress}}
  ingresses:
    - {{ingress}}
  {{/if}}
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: {{db_tier}}
        diskAutoresize: true
        databases:
          - name: syfo-arkivering-db
  accessPolicy:
    outbound:
      external:
  {{#each external-host}}
        - host: {{this}}
  {{/each}}
  kafka:
    pool: {{kafkaPool}}
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: {{this}}
  {{/each}}

