db_tier: db-custom-1-3840
app: syfo-arkivering
namespace: team-esyfo
team: team-esyfo
kafkaPool: nav-prod
azureTenant: nav.no
cpu: 1000m
memory: 2048Mi
external-host:
  - dokarkiv.prod-fss-pub.nais.io
  - cdn.nav.no
env:
  DOKARKIV_AAD_CLIENT_ID: prod-fss.teamdokumenthandtering.dokarkiv
  DOKARKIV_URL: https://dokarkiv.prod-fss-pub.nais.io
